# Generated by Django 6.0.5 on 2026-05-26 13:08

from django.db import migrations

def populate_variant_images(apps, schema_editor):
    Product = apps.get_model('api', 'Product')
    ProductVariant = apps.get_model('api', 'ProductVariant')
    for product in Product.objects.all():
        display = product.display_image.name if product.display_image else None
        if not product.variants.exists():
            if display:
                ProductVariant.objects.create(
                    product=product, size='LARGE',
                    price=product.base_price or 0,
                    is_available=True, image=display,
                )
            continue
        for v in product.variants.all():
            if not v.image:
                fallback = display or (
                    product.variants.exclude(image='').first()
                    and product.variants.exclude(image='').first().image.name
                )
                if fallback:
                    v.image = fallback
                    v.save()

def noop_reverse(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_is_new_productvariant_image'),
    ]

    operations = [
        migrations.RunPython(populate_variant_images, noop_reverse),
    ]
