# Generated by Django 6.0.5 on 2026-05-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_populate_variant_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='display_image',
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(upload_to='products/variants/'),
        ),
    ]
