# Generated by Django 6.0.5 on 2026-10-07 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_product_discount_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpadCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IpadGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ipad/gallery/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IpadSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idle_seconds', models.PositiveIntegerField(default=60)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('currency', models.CharField(default='ر.س', max_length=20)),
                ('gallery_title_ar', models.CharField(default='تصميمات خاصة', max_length=100)),
                ('gallery_title_en', models.CharField(blank=True, default='Custom Designs', max_length=100)),
                ('gallery_visible', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'iPad settings',
            },
        ),
        migrations.CreateModel(
            name='IpadItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(blank=True, max_length=200)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('size_label', models.CharField(blank=True, max_length=80)),
                ('image', models.ImageField(blank=True, upload_to='ipad/items/')),
                ('detail_image', models.ImageField(blank=True, upload_to='ipad/details/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.ipadcategory')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipad_items', to='api.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
